# Site settings
title: David Thunman
email: hello@davidthunman.com
description: > # this means to ignore newlines until "baseurl:"
  An impostor's website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.davidthunman.com" # the base hostname & protocol for your site
twitter_username: david_thunman
github_username: davthu

# Build settings
markdown: kramdown
