# Site settings
title: David Thunman
email: hello@davidthunman.com
description: > # this means to ignore newlines until "baseurl:"
  The professional website of David Thunman
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidthunman.com" # the base hostname & protocol for your site
twitter_username: david_thunman
github_username: jekydavthull

# Build settings
markdown: kramdown
